### ISSUE TITLE
Support fetching location by id

### ISSUE THREAD

**Issue by jozefspisiak** [kiwicom/graphql#11]
User story: When returning user comes to the website, we want him to be able to be able to perform search from the previous search history in place picker. We also want user to be able in the future mark certain flights as favorites and show them in a special menu for the user.

This functionality requires us to save `locationId`s in the locals storage and load locations based on those IDs from API. For this call we can use `locationId` parameter in the `allLocations` call or implement it as a separate call, what makes more sense for the current state of graphql server.

**Comment by michalsanger** [comment]
@jozefspisiak so the use-case is "I have one locationID and I want data for that location"? Then new query `location(id: !ID): Location` would make sense to me.

**Comment by mrtnzlml** [comment]
@michalsanger Please, think about opaque IDs while implementing this.

**Comment by michalsanger** [comment]
@mrtnzlml how about first check if `id` is opaque then call REST API with it's value or with whole `id`.

Second option could be `location(id: ID, locationId: String): Location` with checking that only one input param is set.

**Comment by michalsanger** [comment]
Yeah, but currently the future users of this graphql have some use-cases and do we want to dictate them that they should start using different IDs, explaining again and again what is opaque ID etc?

I'm more into enabling both inputs, measure what's used and then suggesting better approach.

**Comment by jozefspisiak** [comment]
@michalsanger actually, now that you mention it, we would prefer possibility to fetch by array of ids, since we usually need to fetch locations for both from and to in the history and for all flights in general.

**Comment by michalsanger** [comment]
@jozefspisiak sure we can provide query that accepts array of IDs, but maybe it's not needed. Once you have query for one ID, you can compose it like this (example with hotels):
https://goo.gl/k6nUgN

**Comment by mrtnzlml** [comment]
> ...do we want to dictate them that they should start using different IDs, explaining again and again what is opaque ID etc?

Yes, because from our point of view it's again and again but they don't know good practices yet. But I honestly kind of given up so don't do it at all if you don't think the opaque ID is a good way to go. I had this conversation so many times and I don't want to talk about it again.

For me: yes, it's the right way especially because of client and I am going to do it on my projects but no, it's not necessary.

**Comment by mrtnzlml** [comment]
> actually, now that you mention it, we would prefer possibility to fetch by array of ids

I believe this is actually implemented internally so it should be really easy to allow this (even without BC break).
