### ISSUE TITLE
Use fakers instead of storing multiple bookings snapshots

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/graphql#114]
- Create flow type for Booking API responses for Multicity, Return and One way bookings
- Use https://github.com/marak/Faker.js/ or https://github.com/boo1ean/casual to generate fake data for Multicity, Return and One way bookings (json for all three types is almost identical and differs only in details, so it shouldn't be necessary to create three huge fakers, but only one)
- Use these fakes instead of snapshot data

**Comment by mrtnzlml** [comment]
@jaroslav-kubicek Are you going to work on it or can I close it? You can use our private Slack if you are interested only in discussion and you don't consider this to be a real issue... 🙂
