### ISSUE TITLE
Add missing unit tests for business logic in Booking types

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/graphql#116]
Based on the discussion in #109  and #94, add missing unit tests verifying just business logic itself, especially these functions:

src/booking/dataloaders/ApiSanitizer.js - `detectType` function
src/booking/types/outputs/BookingMulticity.js - `createTrips` function
src/booking/types/outputs/BookingReturn.js - `splitLegs` function

**Comment by mrtnzlml** [comment]
@jaroslav-kubicek Are you going to add the tests or not? Newcomers should not be fixing your unfinished work. If not just please close it...

**Comment by jaroslav-kubicek** [comment]
Hmm, it's actually finished work if I'm correct, I eventually did it, but forgot to close this (🙈 ): https://github.com/kiwicom/graphql/blob/master/src/booking/dataloaders/__tests__/ApiSanitizer.test.js
Also, I didn't intend to pass it to newcomers, if I said that, please slap me.

**Comment by mrtnzlml** [comment]
Yes, you marked it as a "good first issue". It's not.

I am really confused by the link you posted because the point of this issue was to create _unit tests verifying just business logic itself_ of the three mentioned functions but the functions are not unit-tested. Nevermind, but it's a pity... 🤷‍♀️

**Comment by jaroslav-kubicek** [comment]
I see it was you 😄 

It was moved to sanitizer, that's why I sent such link: https://github.com/kiwicom/graphql/blob/master/src/booking/dataloaders/ApiSanitizer.js
