### ISSUE TITLE
Allow querying allBookings from localhost

### ISSUE THREAD

**Issue by tbergq** [kiwicom/graphql#117]
In production I can log in and execute query. On localhost I have to use postman, because there is no way to log in, or add access token.

![skjermbilde 2018-05-03 kl 12 08 23](https://user-images.githubusercontent.com/7705041/39571346-6fb53790-4ecb-11e8-9578-0c8a27d6e262.png)

**Comment by jaroslav-kubicek** [comment]
Probably solved by #125

**Comment by mrtnzlml** [comment]
I think the problem here is different. It's just hard and very unclear how to query bookings in our environment...

**Comment by michalsanger** [comment]
Is the solution to opensource this GraphiQL? https://kiwi-graphiql.now.sh/
