### ISSUE TITLE
Add "nearestLeg" field to "BookingInterface" type on frontend

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/graphql#129]
Suggested final GraphQL structure:

```
interface BookingInterface {
  id: ID!
  databaseId: Int
  status: BookingStatus
  price: Price
  allowedBaggage: AllowedBaggage
  assets: BookingAssets
  nearestLeg: Leg
}
```

Pros
- no need to write logic on the client that will iterate over all Legs to retrieve the nearest departure

Cons
- data might get stale if an item is stored in a cache for a longer time, but I guess it's the responsibility of the client to take care of that.

*alternative approach* - add `legs` field as a simple flat list, just like good old deprecated `Booking.legs`

**Comment by mrtnzlml** [comment]
Can you please elaborate more the final graph structure? (how should the result look like)
