### ISSUE TITLE
Bookings: use 'KW-Simple-Token' header instead of 'simple_token' URL parameter

### ISSUE THREAD

**Issue by mrtnzlml** [kiwicom/graphql#134]
Currently, we are calling backend booking API with `?simple_token=` parameter in the URL. We should use `KW-Simple-Token` header instead (requested by our booking backend team).

See: https://github.com/kiwicom/graphql/search?utf8=%E2%9C%93&q=%22simple_token%22&type=

**Comment by michalsanger** [comment]
Value of the header is same as the URL parameter?

**Comment by mrtnzlml** [comment]
Header `KW-Simple-Token` is not supported for this operation at this moment.
