### ISSUE TITLE
Support fetching by slug and radius

### ISSUE THREAD

**Issue by jozefspisiak** [kiwicom/graphql#16]
User story: when you enter on the site by clicking on specific search URL, user wants to load a form with pre-filled locations and map with rendered data points as fast as possible. 

GraphQL should therefore support fetching all locations from slug and radius (which we get from this URL for example: https://www.kiwi.com/en/search/bratislava-slovakia-169km/56.25-19.42-250km) in order to support that. For now we filter them by cities only, it is possible that we would use stations/airports in the future as well for specific cases.

**Comment by michalsanger** [comment]
Would new input `slugRadius: String` of `allLocations` query solve this issue? 

Value of the input would be e.g. `bratislava-slovakia-169km` or `56.25-19.42-250km`, GraphQL would parse the text, fetch location by slug, get it's lat/lng, construct radius and load all locations in that radius.

Is the unit going to be only `km`?

**Comment by jozefspisiak** [comment]
Yes, that would be perfectly fine. Km is the only unit. We can handle the lng lat format with current existing call just fine, but I could remove some code if it supports this format too from our side.
