### ISSUE TITLE
Locations refactoring

### ISSUE THREAD

**Issue by michalsanger** [kiwicom/graphql#17]
- [x] add opaque ID
- [x] enable opaque ID as input in Location dataloder
- [x] `src/flight/types/outputs/RouteStop.js` should call `location.loadById`
- [x] remove `load` and `loadMany` from `src/location/dataloaders/Location.js`
- [x] rename `LocationSuggestions` -> `Locations`
- [x] rename methods in LocationSuggestions:
	`load` -> `loadAll`
	`loadByKey` -> `loadByTerm`
	`loadMany` -> `loadByTerms`

**Comment by mrtnzlml** [comment]
@michalsanger Are you going to continue with this or we can close it?

**Comment by michalsanger** [comment]
@mrtnzlml keep it here please, it's still valid. It doesn't have to be me who implements it

**Comment by mrtnzlml** [comment]
Ok. I don't believe someone else will actually implement it. It's too ambitious with unclear intentions... 🙂 Hopefully, I am wrong.

**Comment by jaroslav-kubicek** [comment]
Would be also nice to remove the necessity to pass `locale` from resolvers and instead provide it when dataloader is created. See FAQ* dataloaders for example.

The only question that remains is whether we want to support a deprecated way of specifying the locale - via query args.

**Comment by jaroslav-kubicek** [comment]
ok, that's true, it's already used. Then ignore my comment for now, it would just complicate things now.

**Comment by mrtnzlml** [comment]
Well, but the first part is absolutely valid - we have to refactor it to use the HTTP header because we are now sending only the header I think. It's now way more important than renaming loader methods...

**Comment by mrtnzlml** [comment]
@radkag This can be closed, right? 🙂

**Comment by radkag** [comment]
@mrtnzlml yes, i was thinking why is it still open. :))

**Comment by mrtnzlml** [comment]
@radkag I am really confused by this development style - seems like it's not fixed yet: https://github.com/kiwicom/graphql/pull/187?

**Comment by radkag** [comment]
@mrtnzlml Yes, I should not close it.
