### ISSUE TITLE
Add mutation for forgotten password 

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/graphql#176]
- Mutation should accept user email as argument
- Send POST request to `https://auth.skypicker.com/v1/user.resetPassword` 
- payload should be `{ login: 'userEmail@example.com' }`
- Authorization: `Basic ${config.auth.basicToken}` needs to be included in HTTP headers

**Comment by jaroslav-kubicek** [comment]
Hmm, I got even better idea now:
- Do not accept email as argument 
- Fetch user info based on login token sent in header to get the email 
- use retrieved email to call REST api for forgotten password 

What do you think? Random ping @michalsanger and @mrtnzlml

**Comment by mrtnzlml** [comment]
@jaroslav-kubicek How are you going to reset the password for not-logged users or different users than you in general?

**Comment by jaroslav-kubicek** [comment]
My idea was to disallow such possibility - just resetting the password for currently  logged in user?

**Comment by mrtnzlml** [comment]
The title of this issue is _Add mutation for **forgotten password**_. So you will have to login first using your password to get your forgotten password? 😊

**Comment by jaroslav-kubicek** [comment]
Oh, I’m very special kind of stupid, nevermind 🤦‍♂️
