### ISSUE TITLE
Allow for "bookingUrl" to accept an optional arg

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/graphql#183]
`bookingUrl` fields now returns full url with `https://kiwi.com` domain, which creates the confusion on staging, because it redirects user to different domain where he isn't logged in.

```
absoluteUrl: bookingUrl
absoluteToo: bookingUrl(true)
relative: bookingUrl(false)
```

So I suggest to implement some arg `absoluteUrl?: Boolean = true` probably?
In case it's false, then it would return relative url in format like this: `//lang/content/manage/XXX`
Not high priority though...

**Comment by michalsanger** [comment]
How about `bookingUrlRelative` property, would that help?

**Comment by jaroslav-kubicek** [comment]
that would help, I somewhat prefer field arg though ... 👼

**Comment by mrtnzlml** [comment]
My 50 cents to the game:

```
bookingUrl(basePath: "https://kiwi.com")   # this is going to the befault value
bookingUrl(basePath: "https://staging-kiwi.com")
bookingUrl(basePath: "https://whitelabel-kiwi.com")
```

I consider changing return value based on the boolean parameter to be an antipattern.

**Comment by git-toni** [comment]
@mrtnzlml I agree with your 50cents. 
Would you however consider a meaning change something like `bookingUrl(baseUrl: "")` as a way to get the path? ie. Would you force the `baseUrl` arg non-empty?

**Comment by mrtnzlml** [comment]
Yes, `baseUrl` should be always non-empty (but optional). It would make sense to return "URL/URI" object instead of string though:

```graphql
type URL {
  absoluteUrl: string
  path: string
  baseUrl: string
  # ...
}
```

> something like bookingUrl(baseUrl: "") as a way to get the path

I don't like it because you are explicitly requesting "URL" but you are getting "path" back. It's similar to what I think is wrong with `bookingUrl(false)`.

**Comment by mrtnzlml** [comment]
Closing. Not needed. See: https://github.com/kiwicom/smart-faq/pull/403

**Comment by git-toni** [comment]
My bad, thanks!
