### ISSUE TITLE
Move from Serverless to Docker environment

### ISSUE THREAD

**Issue by mrtnzlml** [kiwicom/graphql#2]
We are responding with huge JSONs especially because of tracing data (>6MB). But this is limit of AWS Lambda. We need to be able to send much more if needed and not just fail. Docker will solve this and it will simplify our stack (it should contain Apollo Engine as well)...

**Comment by Fallion** [comment]
Strip tracing info: https://github.com/apollographql/apollo-engine-js/issues/56

**Comment by mrtnzlml** [comment]
@Fallion Before you start doing things - all is basically prepared and I just need to finish automatic deployments (see `open-source/graphql` private repo) and switch traffic (without outage!).

**Comment by mrtnzlml** [comment]
Reopening because there are still things to do:

- [ ] use `graphql.kiwi.com` URL (after testing)
- [ ] remove SLS deployment and SLS code from this repo
- [ ] cleanup AWS accounts (also remove chatbot)
- [ ] refactor Apollo Engine (new issue for this will follow)

**Comment by mrtnzlml** [comment]
I think it's a good time for this:

> use graphql.kiwi.com URL

Can you do it please or should I ping someone? It must be without outage...

**Comment by michalsanger** [comment]
@mrtnzlml who are you asking?

**Comment by mrtnzlml** [comment]
Well, originally @Fallion but now both of you... 😊

**Comment by mrtnzlml** [comment]
@michalsanger Please tell me the direction of this project from your point of view? Are we going back to SLS environment or not? We want to start maintaining this project better and would be really helpful to know this information. Thanks.

**Comment by Fallion** [comment]
The main problem with SLS remains Apollo Engine. We have no alternative yet or a properly set up Apollo Engine with SLS.

**Comment by mrtnzlml** [comment]
@Fallion OK so is anyone working on fixing this issue or are we just waiting for something? 🙂

**Comment by michalsanger** [comment]
I'd like to have it SLS. 

- Apollo Engine - let's see if ElasticSearch & Kibana can OK for us or we need to invest into GraphQL Optics
- pricing - I'm waiting for real API stats so we can estimate spendings
