### ISSUE TITLE
[BookingTimeline] events field should be list of non-null events

### ISSUE THREAD

**Issue by RobinCsl** [kiwicom/graphql#217]

**Comment by mrtnzlml** [comment]
@RobinCsl Why is this change necessary? I am not sure if your eslint rule allows it...

**Comment by RobinCsl** [comment]
I just tried, and the eslint rule does not allow it. So I will close this and do differently in RN. However, there are still some components using
```
new GraphQLNonNull(new GraphQLList(new GraphQLNonNull(someGQLtype)))
```

**Comment by mrtnzlml** [comment]
Where? We allow this in the input types (arguments). I agree that in this case, it would maybe make sense to have it non-null though...

**Comment by RobinCsl** [comment]
You're right, they're allowed in input types.
I will try to do differently for now, and we can change it later on if need be.
