### ISSUE TITLE
Support ordering param for allDynamicPackages query

### ISSUE THREAD

**Issue by michalsindelar** [kiwicom/graphql#220]
- Support ordering param so that client can choose which ordering will use

**Comment by michalsanger** [comment]
@michalsindelar  Any docs of what Logitravel supports for ordering plz?

**Comment by michalsindelar** [comment]
Perfect docs follows:

+ The ordering value. Price by default. Available values are:
   + 0-The product price
   + 1- The hotel category
   + 2- The hotel rating

+  The ordering type. Ascending by default. Available values are:
   +  -1 (Descending)
   +    1 (Ascending)
