### ISSUE TITLE
Unify the way how to retrieve the original id

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/graphql#232]
- deprecate all `databaseId` & `originalId`
- parametrize ID field -> `id(unmasked: true)` to retrieve the original id

https://github.com/kiwicom/graphql/pull/227#discussion_r197434788

**Comment by mrtnzlml** [comment]
Hah, that was just a random idea. 😊

Other ideas:

- `id(unmasked: true)` (default always `false` - masked/opaque)
- `id(opaque: false)` (default always `true` - masked/opaque) - this is imho the best
- `id @unmasked`

**Comment by mrtnzlml** [comment]
FYI: we went the `id(opaque: true|false)` direction on one different project...
