### ISSUE TITLE
hotelsCities query must allow all languages

### ISSUE THREAD

**Issue by tbergq** [kiwicom/graphql#236]
Now we can just search for english names.

Searches for `Nueva York` or `Praha` gives no results.

**Comment by tbergq** [comment]
@michalsanger when can you implement this?

**Comment by michalsanger** [comment]
@tbergq on it, sorry for delay

**Comment by MRTNKCR** [comment]
@michalsanger Please, ping me once the issue is solved so that I can inform the testers in Brno, thank you.

**Comment by tbergq** [comment]
@michalsanger any update on this issue?

**Comment by michalsanger** [comment]
@tbergq would be done if there wasn't the Summercamp. I'll be back on this once it's over

**Comment by tbergq** [comment]
@michalsanger Ok 😄  🍹
