### ISSUE TITLE
Baggage is buggy

### ISSUE THREAD

**Issue by tbergq** [kiwicom/graphql#253]
Baggage is just wrong. for BID: `6691572`

```
"allowedBaggage": {
        "cabin": [
          {
            "height": 20,
            "length": 55,
            "weight": 10,
            "width": 40
          },
          {
            "height": 20,
            "length": 35,
            "weight": 3,
            "width": 20
          }
        ],
        "checked": [
          {
            "height": 38,
            "length": 70,
            "weight": 20,
            "width": 50
          }
        ]
      }
```

while FE says 2 cabin baggage, 2 personal items and no check bag. 

We should also have types `cabin`, `checked` and `personal item`
Maybe also even `stroller` as I see that in some zeplin slide. 

We should implement this when new baggage endpoint is ready. 

@MRTNKCR any ETA on that?

**Comment by kantord** [comment]
> We should implement this when new baggage endpoint is ready.

Unless the endpoint can be finished in a few days, I would say we should definitely try to fix this at least for a useful subset of the functionality even before the new endpoint is ready - SmartFAQ's master branch is already using this query and it's currently the most important information we need, so this is a huge priority.

The ideal solution would probably be to release a limited version of the new endpoint and base baggage information in GraphQL on that. If that's not possible then we'll have to find a way to do it with the current endpoint - it has to be technically possible given that FE is doing this already.

Pls anyone who has information on this or can help, reach out to me (or anyone on the SmartFAQ team).

**Comment by MRTNKCR** [comment]
@kantord made a research today and the results are not very promising, i would prefer waiting on reliable baggage api endpoint to be created. Discussion kicked off here: https://skypicker.slack.com/archives/C969A0ZRQ/p1531232199000268
