### ISSUE TITLE
Create Pingdom endpoint

### ISSUE THREAD

**Issue by michalsanger** [kiwicom/graphql#259]
URL: `https://graphql.kiwi.com/ping`

response:
```{"pong": true}```

**Comment by mrtnzlml** [comment]
I already requested better PING endpoint. See: https://gitlab.skypicker.com/devops/requests/issues/1415

**Comment by michalsanger** [comment]
@mrtnzlml devops asked for this today, let's upgrade once they start solving that issue

**Comment by mrtnzlml** [comment]
They asked me for the same one month ago and we agreed not to do that this way. 🙄

**Comment by michalsanger** [comment]
This will help with `504`s we are having now, I agree the suggested POST request is better so we will create it once they they will have time for that.

**Comment by mrtnzlml** [comment]
There is no difference. They can check for status code or _"Check for string"_ as Tomáš H. said. Just a different kind of check.

I am hesitating to merge it because you said many times "I'll do it later" without actually doing it... :)

**Comment by michalsanger** [comment]
Requested "pong" response is default for Pingdom, so I guess devops guys will spend 10 secs setting it up for now. I'll implement your solution once devops guys will have time it, I promise :-)

**Comment by milan-seman** [comment]
Sorry I was not up to date, that is why I asked for the most simple way I knew... ping you configured month ago works just perfect and it is also better solution. 
Sorry for confusion @michalsanger @mrtnzlml - also pingdom check was updated so this should be covered.
Once again sorry.

**Comment by michalsanger** [comment]
@milan-seman so the `/ping` route can be removed?

**Comment by milan-seman** [comment]
@michalsanger yes you can remove it
