### ISSUE TITLE
Rename Booking "databaseId" field to "bid"

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/graphql#281]
since "databaseId" is user more and more, let's give it a more appropriate name. e.g. `BID`?

1. deprecate "databaseId"
2. add the same field with better name

**Comment by vborszeki** [comment]
maybe `bookingId` is a bit more descriptive?

**Comment by mrtnzlml** [comment]
Why not just `id`? See #232

**Comment by jaroslav-kubicek** [comment]
hmm, ok, I dunno why I created two issues for similar thing ¯\\_(ツ)_/¯
