### ISSUE TITLE
Add support for skymock

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/graphql#294]
I'm in consideration whether and _how_ to use Skymock in our GraphQL, for testing purposes? Solution for contract tests? As a replacement for actual REST APIs, just like on frontend e.g. during cypress tests? In any case, I think it might be valuable to think how it can fit together.

https://skymock.skypicker.com/

**Comment by mrtnzlml** [comment]
cc @Strajk - we discussed this
