### ISSUE TITLE
Refresh booking datasets used for tests

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/graphql#315]
- Refresh all datasets stored in the repository that are used in tests to match the current REST API structure.
- Strictly differentiate between items retrieved from collection endpoints and single booking endpoint because they differ in what they contain and then use them appropriately in tests.

**Comment by jaroslav-kubicek** [comment]
I still would like to do it though... 😿

**Comment by michalsanger** [comment]
@jaroslav-kubicek you can always reopen the issue once you have time for this
