### ISSUE TITLE
No Data returned for operation on type WhitelabeledServices

### ISSUE THREAD

**Issue by tbergq** [kiwicom/graphql#330]
This happens on about 50% of the requests. Running against localhost does not produce this error

![image 1](https://user-images.githubusercontent.com/7705041/44521319-ed565080-a6d2-11e8-9fd3-e167f5a8e775.png)

example query:
```
singleBooking(id: <bid>, authToken: <auth_token>) {
    ... on BookingInterface {
      availableWhitelabeledServices {
        transportation {
          relevantLocations {
            location {
              name
              countryFlagURL
            }
            whitelabelURL
            date
          }
        }
      }
    }
  }
```

**Comment by mrtnzlml** [comment]
Platform team is currently investigating what is going on. Seems like our deployment is broken.

**Comment by mrtnzlml** [comment]
Should be fixed now.
