### ISSUE TITLE
Make this GraphQL server repo private

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/graphql#347]
we would like to introduce `customerSupport` field with information about which services are allowed for each booking & according to internal RFC, this business logic should be private.

**Comment by mrtnzlml** [comment]
✅

**Comment by mrtnzlml** [comment]
@jaroslav-kubicek Sorry, seems like this repo is not gonna be private after all. Please create a serverless proxy for your service to use it here and hide the implementation details there.
