### ISSUE TITLE
Proxy: tracing doesn't work

### ISSUE THREAD

**Issue by mrtnzlml** [kiwicom/graphql#36]
There is this error in AE:

> This trace information is incomplete. Check the product documentation to properly enable tracing in your GraphQL server and ensure you the latest version of the Engine Proxy is used.

Tracing doesn't work (only timing) and as a consequence, we cannot see error details:

<img width="255" alt="screen shot 2018-03-14 at 16 51 58" src="https://user-images.githubusercontent.com/978368/37417381-0d7b4208-27a8-11e8-8973-3ca7ceb85d73.png">

I am now in the situation where one client fails but I don't know why and where to start.

**Comment by michalsanger** [comment]
Any idea what could be wrong with our setup?

**Comment by mrtnzlml** [comment]
Dunno, I didn't read the docs because I didn't configure it.
