### ISSUE TITLE
Call Kiwi REST API with proper HTTP header

### ISSUE THREAD

**Issue by michalsanger** [kiwicom/graphql#40]
Backend suggest using `User-Agent` header to identify source of the requests. The value should be "graphql"

**Comment by mrtnzlml** [comment]
@michalsanger It was requested for locations only. Is it relevant for other services as well?

**Comment by michalsanger** [comment]
@mrtnzlml oh yes, I forgot. But I'd say it will not hurt to use it for all of our API calls.
