### ISSUE TITLE
Update booking com credentials

### ISSUE THREAD

**Issue by tbergq** [kiwicom/graphql#48]
Query with language `no` returns `403`. This is because of old `BOOKING_COM_TOKEN`, please update this token. 

[Graphql example](https://kiwi-graphiql.now.sh/?query=query%20%7B%0A%20%20availableHotel(search%3A%20%7B%0A%20%20%20%20hotelId%3A%22aG90ZWw6MjIyNTMzOA%3D%3D%22%2C%0A%20%20%20%20checkin%3A%222018-05-05%22%2C%0A%20%20%20%20checkout%3A%222018-05-06%22%2C%0A%20%20%20%20roomsConfiguration%3A%20%5B%7BadultsCount%3A%201%7D%5D%2C%0A%20%20%20%20language%3A%20no%0A%20%20%7D)%20%7B%0A%20%20%20%20hotel%20%7B%0A%20%20%20%20%20%20rooms%20%7B%0A%20%20%20%20%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20description%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20title%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20text%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)

**Comment by michalsanger** [comment]
fixed
