### ISSUE TITLE
Consider using flow types provided by graphql-js

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/graphql#61]
`graphql-js` library already provides the full set of Flow types that can be imported: https://github.com/graphql/graphql-js/blob/433774dd64d43718bc7ac327fb7e5f2bcca0fe8f/src/type/definition.js

example of possible usage for resolver function:

```
resolve: (((ancentor, args, context, info ): string => {
  return `Hello ${args.name || 'world'}`;
}): GraphQLFieldResolver<Parent, ContextType, { name: string }>),
```

**Comment by jaroslav-kubicek** [comment]
it's just topic for discussion, no additional benefit, just possible alternative to our current way:
```
resolve: async (
    ancestor: mixed,
    { language, id }: Object,
    { dataLoader }: GraphqlContextType,
  ) => {}
```

**Comment by jaroslav-kubicek** [comment]
Ok, I suggest to close this issue, I tried to play with it and I don't like the notation much - too much parenthesis 🙃

**Comment by mrtnzlml** [comment]
Alright. Anyway thanks for pointing this out. We can return back to this proposal later. It's good that you read the code of GraphQL.js... 🙂

Closing... 🙃
