### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by oreqizer** [kiwicom/graphql#63]
So I know how to do things

**Comment by mrtnzlml** [comment]
@oreqizer What exactly is not clear so we'll make this file really helpful?

**Comment by oreqizer** [comment]
## Things I missed so far

* API calls guide (using `HttpRequest`)
* How to test things
* More detailed folder structure
* File nomenclature (and nomenclature in general)
* How to update schema
* General info about CI, releasing etc.
