### ISSUE TITLE
Parametrize logoUrl field of Airline type

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/graphql#67]
Kiwi.com CDN contains airline logos in various sizes - 16, 32, 64, but right now we are returning just one fixed size - 64. We could add optional field parametrization to support all variants.

The possible outcome could be something like this:

```
{
  allFlights(search: {from: [{location: "Prague"}], to: [{location: "Barcelona"}], date: {exact: "2018-05-01"}}, first: 1) {
    edges {
      node {
        legs {
          airline {
            dontCare: logoUrl
            logoUrl: logoUrl(size: M)
            logoUrlRetina: logoUrl(size: L)
          }
        }
      }
    }
  }
}
```

**Comment by mrtnzlml** [comment]
Maybe something like `logoUrl(size: 16)` would be more future friendly? I don't think it's necessary to introduce new XL, XXL, parameters... :)

**Comment by mrtnzlml** [comment]
@jaroslav-kubicek Is there still valid use-case for this? Looks like a stale issue after almost 3 weeks. I would prefer to close it if there is no use-case so we do not create something we don't need...

**Comment by mrtnzlml** [comment]
Please send PR if you really need it. Closing in order to keep this proxy small and also because it's not needed at this moment.
