### ISSUE TITLE
Add FAQArticle voting mutation

### ISSUE THREAD

**Issue by git-toni** [kiwicom/graphql#69]
Wrap this endpoint here https://gitlab.skypicker.com/django-team/knowledgebase#article-voting
to be able to vote or unvote articles of the FAQ.

Definition:

`mutation FAQArticleVote(vote: "up" | "down") : FAQArticle`

**Comment by michalsanger** [comment]
Can you also suggest the requested mutation in the description?

**Comment by git-toni** [comment]
Backend Article voting endpoint will disappear and we're moving to article comments instead. So this issue is no longer relevant.
