### ISSUE TITLE
Remove deprecation from databaseId on Booking type

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/graphql#70]
In order to be able to fetch & display booking ID, let's remove deprecation from `databaseId` on `Booking` type.

BID should be normally accessible as it's one of the main information used by CS when dealing with issues. It's used for e-mail communication and Manage my booking.

**Comment by mrtnzlml** [comment]
Makes sense. However, try to stick with the `id` field if you don't need to display it to the user.

**Comment by jaroslav-kubicek** [comment]
Thanks! We will do, that's also the reason why I explicitly stated that it's used for communication with support.
