### ISSUE TITLE
Add "type" field to Booking type

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/graphql#76]
Let's add `type` field to `Booking` type as this functionality is missing in current implementation and it's necessary to detect whether there is a return flight or multiple stopovers.

It should be an enum, currently with possible values `ONE_WAY`, `RETURN` and `MULTICITY`.
Definition of multicity - `segments` field in Booking API response is non-empty array AND there is no leg with `return=1` - needs further clarification that it's correct like this.

**Comment by mrtnzlml** [comment]
> needs further clarification that it's correct like this

Please ask someone from FE/mobile/booking API devs.
