### ISSUE TITLE
Support location search limited to another location

### ISSUE THREAD

**Issue by michalsanger** [kiwicom/graphql#8]
Motivation: "is there a possibility to query all airports from certain continent, country, or city?"

REST pattern: `?type=subentity&term=<id_of_location>&location_types=airport`

Example (all active airports in london): https://api.skypicker.com/locations/?type=subentity&location_types=airport&term=london_gb

Help wanted: query design suggestion. New param or new query?

**Comment by mrtnzlml** [comment]
> Help wanted: query design suggestion. New param or new query?

Probably query.

**Comment by michalsanger** [comment]
So what about this?
```
allSubLocations(
  locationId: String!,
  options: LocationsOptionsInput
) LocationConnection
```

**Comment by mrtnzlml** [comment]
Maybe. I would prefer to find a real use-case for this query and do something like `suggest[Sub]Locations` instead of creating one generic query for everyone.

**Comment by michalsanger** [comment]
Well, we can always create query with better name later and deprecate this one :-)

**Comment by jozefspisiak** [comment]
Real use case is for new place picker to display all airports in certain city right now. 

In the future we might do some more suggestions for locations, when we have added geographical areas like Nordics or Europe or I saw also possibility to add Beaches or Mountains as categories of interests.
