### ISSUE TITLE
Make "findOne" queries to return non-nulls

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/graphql#81]
We have several queries that have one in common: they accept one param, usually `ID` and return single entity - `Booking`, `FAQArticle` etc. Also, dataloaders are usually defined in a way that they correctly throw an Error if nothing is found.

Yet they are defined as nullable, e.g. booking query

```
export default {
  type: GraphQLBooking, // may be null (doesn't exist)
}
```

... which doesn't make sense in combination with dataloader behaviour.

Additionally, add info about this expected characteristic into CONTRIBUTION guide - that "findOne" queries should always throw an error on 404, return non-null entity and probably accept opaque ID from related "findMany" query if there is such query

**Comment by mrtnzlml** [comment]
I don't understand why it doesn't make sense and what are the benefits of making these queries non-null. Can you please elaborate more on better examples?

**Comment by jaroslav-kubicek** [comment]
I mean - if such queries are expected to always return something or fail otherwise, then it makes sense to create them non-nullable by definition, not just by the inner implementation.

**Comment by mrtnzlml** [comment]
There are three cases:

1. result is returned
2. there is no result but that may happen
3. there is an error

How would you describe the second case? For example "Is user registered?" - I don't consider this to be an error if there is not a user. Or "suggest something" - it's fine in my opinion to return "nothing" if there is really nothing to suggest (there are basically no suggestions but that's not an error).

**Comment by mrtnzlml** [comment]
Still:

> I don't understand why it doesn't make sense and what are the benefits of making these queries non-null.

The only difference I can see so far is that instead of returning this:

```json
{
  "data": {
    "location": null
  },
  "errors": ...
}
```

We'll return this:

```json
{
  "data": null,
  "errors": ...
}
```

What am I missing? This is what is bothering you?

**Comment by jaroslav-kubicek** [comment]
It's not bothering me, it's just proposal for change to think about that more philosophically 💭 

IMHO it would make sense since it's either found and returned or it throws an error.
