### ISSUE TITLE
Replace 'lodash' with 'ramda'

### ISSUE THREAD

**Issue by oreqizer** [kiwicom/graphql#97]
Lodash is a pain in the ass to work with, is [incorrect type-wise](https://github.com/lodash/lodash/issues/3513), has weak FP support (`_.flip` doesn't work at all for example).

Lodash in 2k18 lul

**Comment by mrtnzlml** [comment]
> Lodash in 2k18 lul

Thanks for the motivation. Are you going to send PR, please?

**Comment by oreqizer** [comment]
Done
